 <!-- Modal -->
 <modal-link showOptional="true" idModal="modal1" gambar="img/Pengadaan Barang Jasa.png" judul="Pengadaan Barang / Jasa Pemerintah" isi="Sistem Layanan Pengadaan Secara Elektronik (LPSE) merupakan sistem pengadaan barang/jasa pemerintah yang dilaksanakan secara elektronik dengan memanfaatkan dukungan teknologi informasi. Sistem LPSE ini bertujuan untuk meningkatkan efisiensi, efektivitas, mutu, dan transparansi dalam pelaksanaan pengadaan barang dan jasa. Untuk informasi lebih lanjut layanan lengkap lihat di " link="http://lpse.purwakartakab.go.id/eproc4" isiLink="http://lpse.purwakartakab.go.id/eproc4"></modal-link>
 <modal-biasa idModal="modal2" gambar="img/M-Cap.png" judul="M-CAP" isi="MCAP atau MOBILE COMMUNITY ACCESS POINT adalah mobil berisikan komputer dan layanan internet mobile yang ditujukan dalam diseminasi teknologi informasi guna terwujudnya Purwakarta Cyber District.bagi rekan-rekan baik instansi, lembaga, ataupun sekolah yang ingin di fasilitasi untuk layanan M-CAP bisa menghubungi ke info@ diskominfo.purwakartakab.go.id"></modal-biasa>
 <modal-biasa idModal="modal3" gambar="img/Pertunjukan Rakyat.png" judul="Pertunjukan Rakyat" isi="Pertunjukan rakyat pada umumnya adalah kesenian tradisional yang dipentaskan didepan khalayak terutama sebagai sarana hiburan yang memiliki sifat komunikatif, sehingga bentuk kesenian tersebut juga dapat menjadi sarana pendidikan,kontrol sosial dan sarana penyampaian informasi. Unsur menghibur secara tradisional dan bersifat komunikatif dari pertunjukan kesenian tersebut sangat memudahkan para khalayak untuk menangkap pesan-pesan yang disampaikannya, sehingga dapat digunakan sebagai media komunikasi yang efektif tanpa harus kehilangan fungsinya sebagai media hiburan. Kesenian tradisional juga sebagai karya leluhur bangsa yang merupakan kekayaan dan asset bangsa yang harus dilestarikan, diberdayakan dan dimanfaatkan utnuk kesejahteraan rakyat dengan mendayagunakannya dalam penyelenggaraan pemerintahan, pembangunan dan kemasyarakatan. "></modal-biasa>
 <modal-biasa idModal="modal4" gambar="img/Fasilitas WIFI.png" judul="Fasilitas WIFI" isi="Pemasangan akses point berupa wifi/hotspot di beberapa titik ruang publik yang ada di Kab/kota di wilayah Kabupaten Purwakarta merupakan fasilitas yang disediakan untuk dimanfaatkan oleh masyarakat. Fasilitas wifi sebagai bentuk kepraktisan teknologi, yang saat ini sudah menjadi kebutuhan dalam mengakses internet secara sehat dan mentransfer data, dapat membantu mengurangi penggunaan kertas (paperless). "></modal-biasa>
 <modal-biasa idModal="modal5" gambar="img/Leaflet.png" judul="Leaflet" isi="Leaflet yang merupakan sebuah kertas kecil seperti booklet tak berjilid, juga menjadi salah satu media publikasi yang efektif dalam menginformasikan berbagai program, kegiatan, dan produk Diskominfo Kabupaten Purwakarta kepada masyarakat. Leaflet tersebut bisa didapatkan saat acara tertentu atau saat berkunjung ke Kantor Diskominfo Kabupaten Purwakarta. "></modal-biasa>
 <modal-biasa idModal="modal6" gambar="img/Media Sosial.png" judul="Media Sosial" isi="Media Sosial, sebuah media online yang disediakan untuk memudahkan masyarakat mendapatkan informasi ter-update mengenai program dan kegiatan Diskominfo Kabupaten Purwakarta serta perkembangan teknologi dan informatika di Kabupaten Purwakarta. Media sosial Diskominfo Kabupaten Purwakarta merupakan sebuah jejaring sosial yang saling menghubungkan untuk berbagi informasi dan berkomunikasi dengan instansi, lembaga, tokoh, dan masyarakat umum, yang bisa diakses kapan saja dan dimana saja. Beberapa media sosial Diskominfo Kabupaten Purwakarta yang dapat diakses saat ini adalah Twitter, Facebook, Instagram, dan Youtube. "></modal-biasa>
 <modal-biasa idModal="modal7" gambar="img/Ruang internet publik.png" judul="Ruang Internet Publik" isi="Munculnya jaringan internet menjadi sebuah revolusi dalam dunia komunikasi dan informasi. Untuk memudahkan masyarakat mengaksesnya, maka Diskominfo Kabupaten Purwakarta menyediakan ruang internet yang dapat dimanfaatkan oleh publik, terletak di Kantor Diskominfo Purwakarta Jl. Gandanegara No.25, Nagri Kidul, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat "></modal-biasa>
 <modal-biasa idModal="modal8" gambar="img/Intership.jpg" judul="Internship / PKL" isi="Praktek Kerja Lapangan (PKL) merupakan bentuk implementasi secara sistematis dan sinkron antara program pendidikan di sekolah dengan program penguasaan keahlian yang diperoleh melalui dunia kerja. PKL adalah suatu proses pembelajaran dan pelatihan secara praktis dalam bidang kompetensinya masing-masing, hal ini dimaksudkan untuk memberikan pengalaman nyata bagi peserta didik tentang lingkungan, etos dan budaya kerja yang belum dapat disampaikan sepenuhnya di sekolah. Diskominfo Kabupaten Purwakarta bekerjasama dengan Sekolah Menengah Kejuruan (SMK) dan Perguruan Tinggi, baik yang berada di Purwakarta maupun di luar Purwakarta dalam menyelenggarakan Praktek Kerja Lapangan khususnya di bidang komunikasi dan informatika bagi pelajar dan mahasiswa. Berikut ini adalah daftar SMK dan Perguruan Tinggi yang telah berkerjasama dalam penyelenggaraan PKL di Diskominfo Kabupaten Purwakarta Daftar PKL Diskominfo"></modal-biasa>
 <script src="./js/modal.js"></script>
 <script>
     // Initialization for ES Users
     import {
         Modal,
         Ripple,
         initTE
     } from "tw-elements";

     initTE({
         Modal,
         Ripple
     });
 </script>